[package]
name = "monitor"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.22.4"
reqwest = { version = "0.11.8", features = ["blocking"] }
rand = "0.8.4"
byteorder = "1.4.3"
